### PR TITLE
Warns user if network length is going to be too long, throws an error…

### LINKED ISSUE #105: Path too long error
Trying to run "goquorum wizard" as described here https://docs.goquorum.consensys.net/en/latest/HowTo/GetStarted/Wizard/GettingStarted/ but none of the nodes would start - I figured out that the problem is my working dir path is too long (the error was not obvious, I had to dig into the tessera logs). Changing to a dir with shorter path made it work. 

Error in tessera log 
```
2020-09-21 13:13:27.604 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@53079ae6{/,null,AVAILABLE}
2020-09-21 13:13:27.649 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@295b07e0{HTTP/1.1,[http/1.1]}{0.0.0.0:9081}
2020-09-21 13:13:27.651 [main] INFO  org.eclipse.jetty.server.Server - Started @4221ms
2020-09-21 13:13:27.651 [main] INFO  c.quorum.tessera.server.JerseyServer - Started http://127.0.0.1:9081
2020-09-21 13:13:27.651 [main] INFO  c.quorum.tessera.server.JerseyServer - WADL http://127.0.0.1:9081/application.wadl
ERROR: Cause is Unix socket path too long
```

path that is too long: /Users/sallymacfarlane/workspace/quorum-permissionining-workspace/network/3-nodes-quickstart/

### PR DESCRIPTION
**Pull request by bmcd**
… when generating scripts as well

Fixes #105

### CODE REVIEW

File: src/questions/questions.js [hunk 1]
```diff
@@ -212,10 +225,7 @@ export const NETWORK_CONFIRM = {
 }
 
 export const GENERATE_NAME = {
-  type: 'input',
-  name: 'name',
-  message: 'What would you like to call this network?',
-  validate: (input) => input.trim() !== '' || 'Network name must not be blank.',
+  ...NETWORK_NAME,
```
Comment (apratt3377) [inline src/questions/questions.js:228]: generate_name doesn't have answers.deployment, so the check doesn't get caught in regenerating a network with too long of a name

Comment (bmcd) [reply src/questions/questions.js:216]: good catch, now it loads the config and grabs the deployment similar to how it grabs the existing name

**Review by apratt3377 — APPROVED** [review]
looks good now
